apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::313237845968:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1Q7FR3IUF1OEP
      username: system:node:{{EC2PrivateDNSName}}
    -groups:
      - system:masters
      rolearn: arn:aws:iam::313237845968:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-26T15:57:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1561"
  uid: 79e0b3ba-1579-41be-9c94-67133805255f
